### ISSUE TITLE
System.IO.FileNotFoundException 

### ISSUE THREAD

**Issue by hackabean** [infosecn1nja/SharpDoor#1]
@infosecn1nja  Hey, I just wanted to test out your work, but after successful compilation I get this error:

System.IO.FileNotFoundException: C:\Windows\system32\termsrv.dll
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at SharpDoor.Program.Main(String[] args) in C:\Users\admin2\source\repos\sharpdoor\sharpdoor\Program.cs:line 54

I have checked, that the file exists and has a version that can be patched. I am using:

> OS Name:                   Microsoft Windows 10 Enterprise LTSC
OS Version:                10.0.17763 N/A Build 17763

> 

Any pointers ?

Thanks a lot for sharing.

**Comment by infosecn1nja** [comment]
Hey @hackabean, can you copy again from backup file to C:\Windows\system32\termsrv.dll and and use sharpdoor last update beacuse there is bugs
